-- MySQL Script generated by MySQL Workbench
-- Mon Feb 19 20:37:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema penjualan_barang
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema penjualan_barang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `penjualan_barang` DEFAULT CHARACTER SET utf8 ;
USE `penjualan_barang` ;

-- -----------------------------------------------------
-- Table `penjualan_barang`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penjualan_barang`.`customer` (
  `customer_id` VARCHAR(15) NOT NULL,
  `nama_customer` VARCHAR(35) NULL,
  `kota` VARCHAR(30) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `penjualan_barang`.`produk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penjualan_barang`.`produk` (
  `produk_id` VARCHAR(5) NOT NULL,
  `nama_produk` VARCHAR(25) NULL,
  `group_produk` VARCHAR(25) NULL,
  PRIMARY KEY (`produk_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `penjualan_barang`.`penjualan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penjualan_barang`.`penjualan` (
  `penjualan_id` VARCHAR(10) NULL,
  `tanggal` DATE NULL,
  `customer_id` VARCHAR(15) NOT NULL,
  `produk_id` VARCHAR(10) NULL,
  `qty` INT NULL,
  `fk_customer_id` VARCHAR(15) NOT NULL,
  `produk_produk_id` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`fk_customer_id`, `customer_id`),
  INDEX `fk_penjualan_customer1_idx` (`fk_customer_id` ASC) VISIBLE,
  INDEX `fk_penjualan_produk1_idx` (`produk_produk_id` ASC) VISIBLE,
  CONSTRAINT `fk_penjualan_customer1`
    FOREIGN KEY (`fk_customer_id`)
    REFERENCES `penjualan_barang`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_penjualan_produk1`
    FOREIGN KEY (`produk_produk_id`)
    REFERENCES `penjualan_barang`.`produk` (`produk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
